### ISSUE TITLE
🐞 [Bug]: Dockerfile failing to build

### ISSUE THREAD

**Issue by farhankamalkhan** [restqa/gherkin-linter-action#1]
### What happened?

The following command in the Dockerfile is failing `RUN apk --no-cache add python make g++` and giving the error log
```
ERROR: unable to select packages:
python (no such package):
    required by: world[python]
```

### 🙏 Would you be willing to submit a PR?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by olivierodo** [comment]
Solved #2
